### ISSUE TITLE
支持MM

### ISSUE THREAD

**Issue by darkmoon** [waynell/DialerBox#2]
MM好几个地方发生了变化，1.2可以用，但call log的归属地不显示了。

**Comment by lm789632** [comment]
同 t9拨号可用，但归属地不显示了

**Comment by yv-code** [comment]
@darkmoon @lm789632 @waynell  可以看一下我提的 pull request，支持了 MM

**Comment by darkmoon** [comment]
@waynell 能否提供apk下载？谢谢

**Comment by yv-code** [comment]
@darkmoon 可以到我 fork 的库看看，[地址在此](https://github.com/yellowvii/DialerBox/releases/tag/v1.2.1)，非官方签名，仅供官方升级前临时使用。

**Comment by darkmoon** [comment]
@yellowvii It works. thank you.

**Comment by waynell** [comment]
已经merge @yellowvii 的commit，稍后会打包发布。
